import type { Metadata } from "next";

import OfflineProvider from "@/components/OfflineProvider";
import "./globals.css";
import "./theme.css";
import "./polish.css";
import ServiceWorkerRegister from "@/components/ServiceWorkerRegister";





const themeInitScript = `
(function(){
  try {
    var t = localStorage.getItem('railwork_theme');
    var theme = t === 'dark' ? 'dark' : 'light';
    document.documentElement.setAttribute('data-theme', theme);
  } catch(e) {}
})();
`;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="antialiased"
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body className="min-h-full flex flex-col">
        <ServiceWorkerRegister />
      <OfflineProvider>
        {children}
      </OfflineProvider>
      </body>
    </html>
  );
}
