export const DESIGNATIONS = [
  "DRM",
  "ADRM/OP",
  "ADRM/G",
  "ADRM/Infra",
  "Dy.CTM/CNB",
  "SD/PRYJ",
  "RAJBHASHA ADHIKARI",
  "PRO/PRYJ",
  "Sr.DEN/CO",
  "Sr.DEN/I",
  "Sr.DEN/II",
  "Sr.DEN/III",
  "Sr.DEN/IV",
  "DEN/V",
  "DEN/ESTATE",
  "DEN/TRACK",
  "Sr.DEE/G",
  "Sr.DEE/OP",
  "Sr.DEE/Coaching",
  "Sr.DEE/TRD",
  "Sr.DEE/TRS/CNB",
  "Sr.DEE/TMS/CNB",
  "Principal/ETC/CNB",
  "Sr.DAuo",
  "Sr.DEnHM",
  "Sr.DME/O&F",
  "Sr.DME/Coaching",
  "Sr.DSTE/CO-ord",
  "Sr.DSTE/Signal/PRYJ",
  "Sr.DSTE/CNB",
  "Sr.DSTE/ALJN",
  "Sr.DOM/Co-ord",
  "Sr.DOM/G&G",
  "Sr.DCM/Coaching",
  "Sr.DCM/Freight",
  "Sr.DPO",
  "Sr.DFM",
  "CMS/PRYJ",
  "Sr.DMM",
  "Sr.DSO",
  "Sr.DSC",
  "All BOs",
  "Sr.DCM/Chg & Sr.DSC",
  "All Sr.DENs",
  "All Sr.DSTEs",
  "CPM/GSU",
  "JE/Tele",
  "PS-1",
  "Senior Clerk",
];

export const DEFAULT_DESIGNATION = DESIGNATIONS[0];